import {PostInterface} from '@repo/types';

export const mockPosts: PostInterface[] = [
    {
        "id": "1",
        "author": {
            "id": "001",
            "name": "yong",
            "avatar": "/place-holder.svg"
        },
        "title": "서울 활동메이트 구해요! 파트 절대 X",
        "content": "서울 활영 메이트 구해요 ! (5주, 연말, 연초, 종종, 많달) 서로의 삶을 방해 , 우정도 만들고 싶어요. 사진찌기 서로 좋고 오래있으면서 시간제 - 우주만권 가기.. 맛집, 카페, 먹사거, 핫플같은 감성어야 생활 하고 싶어요. 매주 활영해여^ 오래볼거구, 한달에는 다금 점심요에 이시간도 괜찮에 활형하시도 구해요 ! 위대한 삶에앗 과당과 먹사시 놀이대이구, 랜덤도 구독 밥은 주거리 만들도 놀이더라요. - 사진 측면욥문도 기능 - 저는 주로 여유 받안 하상용 맊라 해보니다. 산머물누 산상을 비용 올일장 나을 알아아서 만내어서 항상화 해이드셔요! 히로 나서히 12시간만 저지활하는 활발은 하루가가 해오세요. 시햬히 사모니 소금을 밤을 종일 많은 알라던 사람 갈하가고 잡결으면 좋겠씁니다. 202일활활, 받로 2-4개활 활도 해봅니다. 시오 활형 정이 욥며 공유하고 싶수있어 말포 맛배시 해오세 좋겠어요. 서로 활영에 동의이 인생은에 좋겠씁니다.",
        "openKakaoTalkLink": "https://open.kakao.com/example",
        "createdAt": "2024-09-08T18:51:00Z",
        "limitApplicant": 5,
        "endDate": "2024-10-08T18:51:00Z",
        "closed": false,
        "type": "ACTIVE",
        "viewCount": 84,
        "modifiedAt": "2024-09-08T18:51:00Z",
        "isTemporary": false,
        "thumbnail": "/place-holder.svg",
        "limitUserCount": 5,
        "appliedUserIds": [],
        "matchedUserIds": [],
        "location": "서울 용산구",
        "hashTags": ["호텔", "공원"],
        "meetingDate": "2024-09-15T11:00:00Z",
        "place": ["서울 용산구"]
    },
    {
        "id": "2",
        "author": {
            "id": "002",
            "name": "yongho",
            "avatar": "/place-holder.svg"
        },
        "title": "경기 같이 사진찍으로 갈분구해요",
        "content": "서울 활영 메이트 구해요 ! (5주, 연말, 연초, 종종, 많달) 서로의 삶을 방해 , 우정도 만들고 싶어요. 사진찌기 서로 좋고 오래있으면서 시간제 - 우주만권 가기.. 맛집, 카페, 먹사거, 핫플같은 감성어야 생활 하고 싶어요. 매주 활영해여^ 오래볼거구, 한달에는 다금 점심요에 이시간도 괜찮에 활형하시도 구해요 ! 위대한 삶에앗 과당과 먹사시 놀이대이구, 랜덤도 구독 밥은 주거리 만들도 놀이더라요. - 사진 측면욥문도 기능 - 저는 주로 여유 받안 하상용 맊라 해보니다. 산머물누 산상을 비용 올일장 나을 알아아서 만내어서 항상화 해이드셔요! 히로 나서히 12시간만 저지활하는 활발은 하루가가 해오세요. 시햬히 사모니 소금을 밤을 종일 많은 알라던 사람 갈하가고 잡결으면 좋겠씁니다. 202일활활, 받로 2-4개활 활도 해봅니다. 시오 활형 정이 욥며 공유하고 싶수있어 말포 맛배시 해오세 좋겠어요. 서로 활영에 동의이 인생은에 좋겠씁니다.",
        "openKakaoTalkLink": "https://open.kakao.com/example",
        "createdAt": "2024-09-08T18:51:00Z",
        "limitApplicant": 5,
        "endDate": "2024-10-08T18:51:00Z",
        "closed": false,
        "type": "ACTIVE",
        "viewCount": 84,
        "modifiedAt": "2024-09-08T18:51:00Z",
        "isTemporary": false,
        "thumbnail": "/place-holder.svg",
        "limitUserCount": 5,
        "appliedUserIds": [],
        "matchedUserIds": [],
        "location": "서울 용산구",
        "hashTags": ["호텔", "호텔", "호텔"],
        "meetingDate": "2024-09-15T11:00:00Z",
        "place": ["서울 용산구"]
    },
    {
        "id": "3",
        "author": {
            "id": "003",
            "name": "yonghochoi",
            "avatar": "/place-holder.svg"
        },
        "title": "대구 활동메이트 구해요! 파트 절대 X",
        "content": "서울 활영 메이트 구해요 ! (5주, 연말, 연초, 종종, 많달) 서로의 삶을 방해 , 우정도 만들고 싶어요. 사진찌기 서로 좋고 오래있으면서 시간제 - 우주만권 가기.. 맛집, 카페, 먹사거, 핫플같은 감성어야 생활 하고 싶어요. 매주 활영해여^ 오래볼거구, 한달에는 다금 점심요에 이시간도 괜찮에 활형하시도 구해요 ! 위대한 삶에앗 과당과 먹사시 놀이대이구, 랜덤도 구독 밥은 주거리 만들도 놀이더라요. - 사진 측면욥문도 기능 - 저는 주로 여유 받안 하상용 맊라 해보니다. 산머물누 산상을 비용 올일장 나을 알아아서 만내어서 항상화 해이드셔요! 히로 나서히 12시간만 저지활하는 활발은 하루가가 해오세요. 시햬히 사모니 소금을 밤을 종일 많은 알라던 사람 갈하가고 잡결으면 좋겠씁니다. 202일활활, 받로 2-4개활 활도 해봅니다. 시오 활형 정이 욥며 공유하고 싶수있어 말포 맛배시 해오세 좋겠어요. 서로 활영에 동의이 인생은에 좋겠씁니다.",
        "openKakaoTalkLink": "https://open.kakao.com/example",
        "createdAt": "2024-09-08T18:51:00Z",
        "limitApplicant": 5,
        "endDate": "2024-10-08T18:51:00Z",
        "closed": false,
        "type": "ACTIVE",
        "viewCount": 84,
        "modifiedAt": "2024-09-08T18:51:00Z",
        "isTemporary": false,
        "thumbnail": "/place-holder.svg",
        "limitUserCount": 5,
        "appliedUserIds": [],
        "matchedUserIds": [],
        "location": "서울 용산구",
        "hashTags": ["호텔", "호텔", "호텔"],
        "meetingDate": "2024-09-15T11:00:00Z",
        "place": ["서울 용산구"]
    },
    {
        "id": "4",
        "author": {
            "id": "004",
            "name": "chan hwi",
            "avatar": "/place-holder.svg"
        },
        "title": "부산 활동메이트 구해요! 파트 절대 X",
        "content": "부산 활영 메이트 구해요 ! (5주, 연말, 연초, 종종, 많달) 서로의 삶을 방해 , 우정도 만들고 싶어요. 사진찌기 서로 좋고 오래있으면서 시간제 - 우주만권 가기.. 맛집, 카페, 먹사거, 핫플같은 감성어야 생활 하고 싶어요. 매주 활영해여^ 오래볼거구, 한달에는 다금 점심요에 이시간도 괜찮에 활형하시도 구해요 ! 위대한 삶에앗 과당과 먹사시 놀이대이구, 랜덤도 구독 밥은 주거리 만들도 놀이더라요. - 사진 측면욥문도 기능 - 저는 주로 여유 받안 하상용 맊라 해보니다. 산머물누 산상을 비용 올일장 나을 알아아서 만내어서 항상화 해이드셔요! 히로 나서히 12시간만 저지활하는 활발은 하루가가 해오세요. 시햬히 사모니 소금을 밤을 종일 많은 알라던 사람 갈하가고 잡결으면 좋겠씁니다. 202일활활, 받로 2-4개활 활도 해봅니다. 시오 활형 정이 욥며 공유하고 싶수있어 말포 맛배시 해오세 좋겠어요. 서로 활영에 동의이 인생은에 좋겠씁니다.",
        "openKakaoTalkLink": "https://open.kakao.com/example",
        "createdAt": "2024-09-08T18:51:00Z",
        "limitApplicant": 5,
        "endDate": "2024-10-08T18:51:00Z",
        "closed": false,
        "type": "ACTIVE",
        "viewCount": 84,
        "modifiedAt": "2024-09-08T18:51:00Z",
        "isTemporary": false,
        "thumbnail": "/place-holder.svg",
        "limitUserCount": 5,
        "appliedUserIds": [],
        "matchedUserIds": [],
        "location": "서울 용산구",
        "hashTags": ["호텔"],
        "meetingDate": "2024-09-15T11:00:00Z",
        "place": ["서울 용산구"]
    },
];
